#!/bin/bash

eval "$( ./login )"

# TODO: Pagination
POST_IDS=( $( curl -sH "Authorization: BEARER $TOKEN" "https://public-api.wordpress.com/rest/v1.1/sites/$BLOG_ID/posts/?number=100" \
	| jshon -e posts -a -e ID -u ) )

for POST_ID in "${POST_IDS[@]}"; do
	MEDIA_ID=$( curl -sH "Authorization: BEARER $TOKEN" "https://public-api.wordpress.com/rest/v1.1/sites/$BLOG_ID/media/?post_ID=$POST_ID&mime_type=image&number=1" |
		jshon -e media -e 0 -e ID -u )

	if [ -z "$MEDIA_ID" ]; then
		echo "$POST_ID: Failed to update - no MEDIA_ID" > /dev/stderr
		continue
	fi

	CHECK_POST_ID=$( curl -sH "Authorization: BEARER $TOKEN" "https://public-api.wordpress.com/rest/v1/sites/$BLOG_ID/posts/$POST_ID" \
		--data "featured_image=$MEDIA_ID" |
		jshon -e ID -u )

	if [ -z "$CHECK_POST_ID" ]; then
		echo "$POST_ID: Failed to update to MEDIA_ID=$MEDIA_ID" > /dev/stderr
	else
		echo "$POST_ID: Updated to MEDIA_ID=$MEDIA_ID" > /dev/stderr
	fi
done
